---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ci-deployment"
spec:
  selector:
    matchLabels:
      app: "ci-deployment"
  replicas: 3 
  template:
    metadata:
      labels:
        app: "ci-deployment"
    spec:
      containers:
      - image: CONTAINER_IMAGE
        imagePullPolicy: Always
        name: "leaseplan"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: "ci-deployment"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: "ci-deployment"